name: Test Workflow

on:
  push:
    branches:
      - main
      - test-data

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run a sample command
        run: echo "Hello from GitHub Actions!"
